// https://docs.google.com/spreadsheets/d/1EgDDWSgJJa5hoAZ_iEy5oHp82r7blH3t-Mtf5IinZH4/edit#gid=718711580
export const socialGroups = {
  en: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  }, 
  ru: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  }, 
  id: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  ms: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  }, 
  es: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  th: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  }, 
  vn: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  }, 
  cn: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  pt: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  tr: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  pl: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  ro: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  me: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  kr: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  in: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  hi: {
    youtube: '',
    facebook: '',
    tw: '',
    ok: '',
    instagram: '',
    tg: '',
    vk: '',
},
  ua: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  kz: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  az: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  fa: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
  br: {
      youtube: '',
      facebook: '',
      tw: '',
      ok: '',
      instagram: '',
      tg: '',
      vk: '',
  },
}
