import payments from './paymentsData';

export const localeGroups = {
  "tr": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.coins, 
    payments.cepbank, 
    payments.neteller, 
    payments.qrcode, 
    payments.jeton_wallet, 
    payments.jeton_voucher, 
    payments.wmz, 
    payments.perfect_money, 
    payments.advcash_wallet, 
    payments.payeer_wallet
  ],
  "vn": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.nganluong_atm_online, 
    payments.internet_banking, 
    payments.nganluong, 
    payments.advcash_wallet, 
    payments.wmz, 
    payments.neteller, 
    payments.perfect_money, 
    payments.nganluong_atm_offline, 
    payments.vnpost, 
    payments.viettelpost
  ],
  "id": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.virtualaccount, 
    payments.internet_banking, 
    payments.fasa_pay, 
    payments.perfect_money, 
    payments.neteller
  ],
  "in": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.indian_exchanger, 
    payments.globe_pay, 
    payments.internet_banking, 
    payments.indian_cash, 
    payments.neteller, 
    payments.perfect_money, 
    payments.payeer_wallet
  ],
  "hi": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.indian_exchanger, 
    payments.globe_pay, 
    payments.internet_banking, 
    payments.indian_cash, 
    payments.neteller, 
    payments.perfect_money, 
    payments.payeer_wallet
  ],
  "br": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.safety_pay, 
    payments.advcash_wallet, 
    payments.neteller, 
    payments.wmz, 
    payments.perfect_money, 
    payments.coins, 
    payments.boleto
  ],
  "es": [ payments.vs_mc_ae_ct, 
    payments.safety_pay, 
    payments.neteller, 
    payments.coins
  ],
  "pt": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.safety_pay, 
    payments.advcash_wallet, 
    payments.neteller, 
    payments.wmz, 
    payments.perfect_money, 
    payments.coins, 
    payments.boleto
  ],
  "cn": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.perfect_money, 
    payments.neteller, 
    payments.coins, 
    payments.wmz
  ],
  "en": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.wmz, 
    payments.neteller, 
    payments.advcash_wallet, 
    payments.perfect_money, 
    payments.coins, 
    payments.payeer_wallet, 
    payments.globe_pay, 
    payments.internet_banking, 
    payments.indian_cash, 
    payments.nganluong, 
    payments.virtualaccount, 
    payments.fasa_pay
  ],
  "kr": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.wmz, 
    payments.neteller, 
    payments.perfect_money, 
    payments.coins, 
    payments.payeer_wallet, 
    payments.advcash_wallet
  ],
  "kz": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.qiwi, 
    payments.advcash_wallet, 
    payments.yandex, 
    payments.wmz, 
    payments.perfect_money, 
    payments.payeer_wallet, 
    payments.coins
  ],
  "ru": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.yandex, 
    payments.qiwi, 
    payments.wmz, 
    payments.neteller, 
    payments.coins, 
    payments.perfect_money, 
    payments.payeer_wallet, 
    payments.advcash_wallet
  ],
  "th": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.card_jcb, 
    payments.internet_banking, 
    payments.neteller, 
    payments.advcash_wallet, 
    payments.coins, 
    payments.perfect_money, 
    payments.wmz
  ],
  "ua": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.qiwi, 
    payments.wmz, 
    payments.yandex, 
    payments.neteller, 
    payments.coins, 
    payments.perfect_money, 
    payments.payeer_wallet, 
    payments.advcash_wallet],
  "az": [ payments.card_visa, 
    payments.card_mastercard, 
    payments.qiwi, 
    payments.yandex, 
    payments.wmz, 
    payments.neteller, 
    payments.coins, 
    payments.perfect_money, 
    payments.payeer_wallet, 
    payments.advcash_wallet
  ],
}
